COMPILER = g++
CFLAGS = -O3 -mcmodel=large -std=c++11 -pthread -I./minisat/

PRE_CFLAGS = ${CFLAGS} -c
TARGET = ScalableCA

SRC_DIR = src

BIN_DIR = bin

MERSENNE = mersenne
MERSENNE_TARGET = ${SRC_DIR}/${MERSENNE}.o
MERSENNE_CC_FILE = ${SRC_DIR}/${MERSENNE}.cc
MERSENNE_H_FILE = ${SRC_DIR}/${MERSENNE}.h
MERSENNE_SOURCE_FILES = ${MERSENNE_H_FILE} ${MERSENNE_CC_FILE}

PBOCCSATSOLVER = pboccsatsolver
PBOCCSATSOLVER_TARGET = ${SRC_DIR}/${PBOCCSATSOLVER}.o
PBOCCSATSOLVER_CPP_FILE = ${SRC_DIR}/${PBOCCSATSOLVER}.cpp
PBOCCSATSOLVER_H_FILE = ${SRC_DIR}/${PBOCCSATSOLVER}.h
PBOCCSATSOLVER_SOURCE_FILES = ${SOLVER_H_FILE} ${SOLVER_CPP_FILE}

EXPANDOR = Expandor
EXPANDOR_TARGET = ${SRC_DIR}/${EXPANDOR}.o
EXPANDOR_CPP_FILE = ${SRC_DIR}/${EXPANDOR}.cpp
EXPANDOR_H_FILE = ${SRC_DIR}/${EXPANDOR}.h
EXPANDOR_SOURCE_FILES = ${EXPANDOR_H_FILE} ${EXPANDOR_CPP_FILE}

OPTIMIZER = Optimizer
OPTIMIZER_TARGET = ${SRC_DIR}/${OPTIMIZER}.o
OPTIMIZER_CPP_FILE = ${SRC_DIR}/${OPTIMIZER}.cpp
OPTIMIZER_H_FILE = ${SRC_DIR}/${OPTIMIZER}.h
OPTIMIZER_SOURCE_FILES = ${OPTIMIZER_H_FILE} ${OPTIMIZER_CPP_FILE}

EXT_MINISAT_TARGET = minisat_ext/Solver.o minisat_ext/Ext.o minisat_ext/BlackBoxSolver.o
EXT_MINISAT_SOURCE_FILES = minisat_ext/Solver.cc minisat_ext/Solver.h minisat_ext/Ext.h minisat_ext/Ext.cc minisat_ext/BlackBoxSolver.h minisat_ext/BlackBoxSolver.cc

TARGET_FILES = 	${MERSENNE_TARGET} \
				${EXPANDOR_TARGET} \
				${OPTIMIZER_TARGET}   \
				${EXT_MINISAT_TARGET} \
				${PBOCCSATSOLVER_TARGET} \


UPDATE = update
CLEAN = clean
CLEANUP = cleanup

MAIN_SOURCE_FILE = ${SRC_DIR}/main.cpp

all: ${TARGET_FILES} ${TARGET} ${UPDATE} ${CLEAN}

${MERSENNE_TARGET}: ${MERSENNE_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${MERSENNE_CC_FILE} -o ${MERSENNE_TARGET}

${PBOCCSATSOLVER_TARGET}: ${PBOCCSATSOLVER_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${PBOCCSATSOLVER_CPP_FILE} -o ${PBOCCSATSOLVER_TARGET}

${EXPANDOR_TARGET}: ${EXPANDOR_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${EXPANDOR_CPP_FILE} minisat/core/Solver.o -o ${EXPANDOR_TARGET}

${OPTIMIZER_TARGET}: ${OPTIMIZER_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${OPTIMIZER_CPP_FILE} minisat/core/Solver.o -o ${OPTIMIZER_TARGET}

${EXT_MINISAT_TARGET}: ${EXT_MINISAT_SOURCE_FILES}
	cd minisat_ext; make -f Makefile extminisat; cd ..

${TARGET}: ${MAIN_SOURCE_FILE} ${TARGET_FILES}
	${COMPILER} ${CFLAGS} ${MAIN_SOURCE_FILE} ${TARGET_FILES} -o ${TARGET}

${UPDATE}:
	chmod +x ${BIN_DIR}/*

${UPDATE}:
	chmod +x ${BIN_DIR}/*

${CLEAN}:
	rm -f *~
	rm -f ${SRC_DIR}/*.o
	rm -f ${SRC_DIR}/*~
	rm -f minisat/utils/*.or minisat/utils/*.o minisat/core/*.or minisat/core/*.o
	rm -f minisat/core/depend.mk
	rm -f ${EXT_MINISAT_TARGET}
	rm -f minisat_ext/depend.mk

${CLEANUP}: ${CLEAN}
	rm -f ${TARGET}